vich_uploader:
    db_driver: orm

    mappings:
      chat_images:
        uri_prefix: /uploads/chats
        upload_destination: '%kernel.project_dir%/public/uploads/chats'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        delete_on_update: false
        delete_on_remove: false


      actualite_images:
        uri_prefix: /uploads/actu
        upload_destination: '%kernel.project_dir%/public%public/uploads/actu'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

